manifest: Don't track Terminal package from LineageOS
* https://github.com/exthmui/android/commit/e6c801d03c01d6846f0132805cddcf2285ae1107 is removed Terminal and libvterm.
  But why add it https://github.com/exthmui/android/blob/exthm-11/default.xml#L560

* This fix:
  error: packages/apps/Terminal.jni/Android bp:1:1: "libjni_terminal" depends on undefined module "libvterm"

Signed-off-by: anrui2032 <anrui2032@gmail.com>